version: "3"

# docker-composes works with services.
services:
  ass-db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ass
      MYSQL_DATABASE: ass
    ports:
      - "3308:3306"
  # Names our volume

  ass-server:
    # build from this directory
    build: ./server
    # use same ports as defined in server.go file
    ports:
      - 425:425

  ass-client:
    build: ./client
    command: npm start
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 420:420

volumes:
  ass-db-volume: {}