version: "3"

# docker-composes works with services.
services:
  assumptionzzz-server:
    build: .
    command: go run ./server.go

    # use same ports as defined in server.go file
    ports:
      - 420:420

  # # Second service (container): the client.
  # # We use the keyword 'client' for the server.
  # client:
  #   # Here 'client/ corresponds to the path to the client folder
  #   # that contains the Dockerfile to use.
  #   build: client/

  #   # The command to execute once the image is created.
  #   # The following command will execute "python ./client.py".
  #   command: python ./client.py

  #   # The keyword 'network_mode' is used to define the network type.
  #   # Here we define that the container can access to the 'localhost' of the computer.
  #   network_mode: host

  #   # The keyword'depends_on' allows you to define whether the service
  #   # should wait until other services are ready before launching.
  #   # Here, we want the 'client' service to wait until the 'server' service is ready.
  #   depends_on:
  #     - server