version: "3"

# docker-composes works with services.
services:
  assumptionzzz-server:
    build: .
    command: go run ./server.go

    # use same ports as defined in server.go file
    ports:
      - 420:420